In [2]:
import pandas as pd

In [3]:
lib_df = pd.read_csv("d:\DIANN-beg\TIM_240819_OPL1041_CdAM_JNL_Plasma_DDA_library_CUMULATIVE_library.tsv", sep='\t')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Admin\AppData\Local\Temp\ipykernel_9900\613859916.py:1: SyntaxWarning: invalid escape sequence '\D'
  lib_df = pd.read_csv("d:\DIANN-beg\TIM_240819_OPL1041_CdAM_JNL_Plasma_DDA_library_CUMULATIVE_library.tsv", sep='\t')

In [4]:
lib_df.columns

Index(['PrecursorMz', 'ProductMz', 'Annotation', 'ProteinId', 'GeneName',
       'PeptideSequence', 'ModifiedPeptideSequence', 'PrecursorCharge',
       'LibraryIntensity', 'NormalizedRetentionTime', 'PrecursorIonMobility',
       'FragmentType', 'FragmentCharge', 'FragmentSeriesNumber',
       'FragmentLossType', 'AverageExperimentalRetentionTime'],
      dtype='str')

In [5]:
dummy = lib_df.apply(lambda row : row["ModifiedPeptideSequence"] + str(row["PrecursorCharge"]), axis=1)

In [6]:
pre_df = pd.read_csv('final_data/lookup.tsv', sep='\t')

In [21]:
len(set(dummy.drop_duplicates().tolist()) - set(pre_df['Precursor'].tolist()))

43708

In [7]:
pre_df

,Precursor,Reference table,Start id,Number of MS/MS
0,AAAFYVR2,0000.tsv,0,12
1,AALHFFNFR2,0000.tsv,20,8
2,AALHFFNFR3,0000.tsv,40,6
3,ADENIIVR2,0000.tsv,60,4
4,ADFEELR2,0000.tsv,80,6
...,...,...,...,...
165743,VHVDFNSYVQSPAYHSPQEDPFLFTYASHPHQQYSLPSK6,1657.tsv,860,2
165744,VQEAPSTEAGAPGPSVLPTPSESQEPGEELPLDRASEYK4,1657.tsv,880,1
165745,VRPHSGKVAGYVPETVPEETGPEAGSSAPGIGGAAEEVGK4,1657.tsv,900,2
165746,VRPHSGKVAGYVPETVPEETGPEAGSSAPGIGGAAEEVGK5,1657.tsv,920,1
165747,YNSC(UniMod:4)RPNMALGHPQLQQVTSPSRPSHAVIPADQDC(...,1657.tsv,940,1

In [8]:
lookup_df = pd.read_csv("final_data\\lookup.tsv", sep='\t')

In [9]:
msms_df = pd.read_csv("final_data\\msms_0001.tsv", sep='\t')

In [14]:
lookup_df.shape

(165748, 4)

In [17]:
lookup_df.query("`Number of MS/MS` > 5")

,Precursor,Reference table,Start id,Number of MS/MS
0,AAAFYVR2,0000.tsv,0,12
1,AALHFFNFR2,0000.tsv,20,8
2,AALHFFNFR3,0000.tsv,40,6
4,ADFEELR2,0000.tsv,80,6
5,ADIWLIR2,0000.tsv,100,19
...,...,...,...,...
165618,VGGSGGGGHGGGGGGGSSNAGGGGGGASGGGANSKPAQK3,1656.tsv,360,7
165619,VGPADDGPAPSGEEEGEGGGEAGGKEPAADAAPGPSAAFR3,1656.tsv,380,20
165620,VHVDFNSYVQSPAYHSPQEDPFLFTYASHPHQQYSLPSK5,1656.tsv,400,7
165621,VLDGLTASSPGSGSSSGSNSGGGAGSGSVHPAGTAGVLR3,1656.tsv,420,14
165704,PLQPLGC(UniMod:4)VPQSVSPSEQALPPHLEPAWPQGLRHNSV...,1657.tsv,80,6

In [11]:
msms_df.columns

Index(['id', 'b1(1+)', 'b2(1+)', 'b3(1+)', 'b4(1+)', 'b5(1+)', 'b6(1+)',
       'b7(1+)', 'b8(1+)', 'b9(1+)',
       ...
       'y30(2+)', 'y31(2+)', 'y32(2+)', 'y33(2+)', 'y34(2+)', 'y35(2+)',
       'y36(2+)', 'y37(2+)', 'y38(2+)', 'y39(2+)'],
      dtype='str', length=157)

In [12]:
train_df = lookup_df.query("`Number of MS/MS` >= 10")
testval_df = lookup_df.query("`Number of MS/MS` < 10 & `Number of MS/MS` > 5")
test_df = testval_df.sample(frac=0.5)
val_df = testval_df.drop(test_df.index)

In [13]:
train_df.shape, testval_df.shape

((52443, 4), (38773, 4))